### ISSUE TITLE
Performance Evaluation

### ISSUE THREAD

**Issue by jimmychiangmtk** [thstkdgus35/ntire-2020-deblur-mobile#2]
Which resolution will be evaluated in final results, `720x1280` or `256x256`?
The reported PSNR is 28.34, which TFLite model produce this result, `deblur.tflite` or others?

**Comment by jimmychiangmtk** [comment]
> We report performances of the provided baseline model. For some hardware-related issues, timings is measured with inputs of 256 x 256 (models/deblur_256.tflite) while 1280 x 720 inputs (models/deblur.tflite) are used to measure PSNR

Is this also the mechanism for final scoring formula?

**Comment by sanghyun-son** [comment]
Yes. The Pixel 4 device has a problem running `720x1280` inputs on GPU, so the speed will be measured using `256x256` inputs.

**Comment by jimmychiangmtk** [comment]
In this case, the participant may needs to submit 2 TFLite files, one is with `720x1280` resolution, the other is with `256x256` resolution.
How to judge these two models are the same?

There is an alternative way to submit only `720x1280` resolution model.
You can set `--input_layer=input_1` and `input_layer_shape=1,256,256,3` flags in `benchmark_model`, so that you can use the full model to check PSNR and run inference in `256x256` resolution.
Is this make sense?

**Comment by jimmychiangmtk** [comment]
> In this case, the participant may needs to submit 2 TFLite files, one is with `720x1280` resolution, the other is with `256x256` resolution.
> How to judge these two models are the same?
> 
> There is an alternative way to submit only `720x1280` resolution model.
> You can set `--input_layer=input_1` and `input_layer_shape=1,256,256,3` flags in `benchmark_model`, so that you can use the full model to check PSNR and run inference in `256x256` resolution.t
> Is this make sense?

Sorry, I found this does not work when there is `TransposeConv` in the model.
`TransposeConv` needs specified `output_shape` in TFLite, and it will not be changed by TFLite interpreter.

**Comment by sanghyun-son** [comment]
Thank you for the detailed feedback.

We will crop `720x1280` image into overlapping `256x256` patches to check consistency between `*.tflite` and `*_256.tflite` models. Specifically, those overlapping patches will be fed to the `*_256.tflite` model individually and then merged after the output layer. We have checked that the result is almost the same as the output of the `*.tflite` model (`720x1280` input).

We will update this instruction and code for the above process.

**Comment by jimmychiangmtk** [comment]
Got it.
In that case, which PSNR should participants report, `256x256` or `720x1280`?
The final quality index is based on `720x1280` and quality of `256x256` is sued to check consistency?
Or is there any other rule?

Thanks.

**Comment by sanghyun-son** [comment]
That's correct. Your submission images should be generated using `720x1280` inputs and `*.tflite` model.

After the final submission, organizers will do some sanity check between `*,tflite` and `*_256.tflite` models to ensure that those models are the same.

Thank you!

**Comment by jimmychiangmtk** [comment]
More questions for performance evaluation.
1. When would you release the scoring policy?
2. Is it possible to use hexagon_delegate in benchmark_model?

Thank you.

**Comment by sanghyun-son** [comment]
We will release the detailed scoring policy in a week. You can also use the hexagon_delegate, but please describe it accurately in your factsheet.

Thank you.

**Comment by jimmychiangmtk** [comment]
Hi, 

I found typo of your scoring formula in the challenge website.
https://competitions.codalab.org/competitions/22234#learn_the_details-evaluation
`Score = PSNR + 0.5 * log_2(MAX(FPS, 45) / baseline_FPS)`
`MAX` should be `MIN`, right?

**Comment by sanghyun-son** [comment]
Thanks for pointing out. We have updated the website!

**Comment by jimmychiangmtk** [comment]
Thanks for your quick update.

Another question regarding to the scoring policy.
We have some results with 3x FPS improvement and 0.6dB drop in PSNR with quantization-aware training, but it has nearly zero gain in the final score.
It seems no benefit to try quantization in the task.
However, we think quantization is important in mobile devices.

Do you have any idea about this question?

Thank you.

**Comment by sanghyun-son** [comment]
We agree that quantization is very important on mobile devices, but the performance also matters.

In general, we consider that the PSNR drop of 0.5dB is quite significant, and changes output results pretty much.

Our evaluation criterion is decided by considering several possible cases and trade-offs.

A similar metric was also used in [PIRM 2018 challenge](http://ai-benchmark.com/challenge.html), which also discounts the final score when the PSNR drops.

We note that our measure weights runtime more as slow models get a penalty from the final score.

Since the provided baseline model is very simple, we expect various novel architectures and techniques for further optimization.

Currently we are not planning to change the evaluation criterion but will discuss the importance of the quantization.

Thank you.

**Comment by SeungjunNah** [comment]
Dear @jimmychiangmtk,

We consider both the accuracy and speed of solutions to be important.
We would like to encourage developing acceleration techniques that could minimize accuracy loss as much as possible.

Quantization roughly brings x3 speed gains for ConvNets while PSNR is expected to go down.
You can achieve +0.8 score by our metric if not plateaued by maximum fps: +1/2 * log_2 (3) ~= 0.8
If PSNR loss is better than -0.8 dB, you will get a higher score than the non-quantized model.

**Comment by jimmychiangmtk** [comment]
Got it.
Thanks for your explanation.
