### ISSUE TITLE
Quantization Isse

### ISSUE THREAD

**Issue by jimmychiangmtk** [thstkdgus35/ntire-2020-deblur-mobile#3]
Hi,

I think there is something wrong when you quantize your model.
Although there is PSNR drop in post-training quantization (~2dB), but the output image should not be corrupted.
We have done post-training quantization experiments with correct results.

Have you tried quantization-aware trianing?

**Comment by sanghyun-son** [comment]
We will check the post-training quantization results. We have some internal experiments on quantization-aware training, and the model worked well with some PSNR degradations.
